version: "3.8"
services:
  postgres:
    container_name: postgres_refugeesysapp
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: refugee_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_refugeesysapp
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: salim@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5058:80"